MVC/MVCLabb/Areas/User/Controllers/AlbumController.cs
using MVCLabb.Areas.User.Models;
using MVCLabb.Areas.User.Mapper;
using MVCLabb.Data;
using MVCLabb.Data.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCLabb.HelperMethods;

namespace MVCLabb.Areas.User.Controllers
{


    [Authorize(Roles = "User")]
    public class AlbumController : Controller
    {
        IUserRepository userRepository;
        IAlbumRepository albumRepository;
        Guid userID; 

        public AlbumController()
        {
            userRepository = new UserRepository();
            albumRepository = new AlbumRepository();
            userID = UserHelper.GetLogedInUser(userRepository).Id;

        }

        public ActionResult Index()
        {

            List<Album> albumsDB = albumRepository.GettAllAlbumsByUserID(userID);
            List<ListAlbumViewModel> albums = new List<ListAlbumViewModel>();
            albumsDB.ForEach(x => albums.Add(AlbumMapper.MapListAlbumViewModel(x)));
            return View(albums);


        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(EditAlbumViewModel model)
        {
            if (ModelState.IsValid)
            {
                Album album = AlbumMapper.MapEditAlbumViewModel(model, userID);
                albumRepository.AddAlbum(album);
               
            }
            return Content(model.Name);
        }

        [HttpGet]
        public ActionResult Edit(EditAlbumViewModel model)
        {

            Album album = albumRepository.GetAlbumByID(model.Id);

            model = AlbumMapper.MapEditAlbumViewModel(album);

            if (album.UserID == userID)
            {
                return View(model);
            }

            return View();
        }

        [HttpPost]
        public ActionResult Edit(EditAlbumViewModel model, FormCollection collection)
        {
            if (ModelState.IsValid)
            {
                Album album = AlbumMapper.MapEditAlbumViewModel(model, userID);

                albumRepository.UpdateAlbum(album);
                
            }
            return Content(model.Name);
        }

        [HttpGet]
        public ActionResult Delete(EditAlbumViewModel model)
        {
            Album album = albumRepository.GetAlbumByID(model.Id);

            model = AlbumMapper.MapEditAlbumViewModel(album);

            if (album.UserID == userID)
            {
                return View(model);
            }

            return View();
        }

        [HttpPost]
        public ActionResult Delete(EditAlbumViewModel model, FormCollection collection)
        {
            Album album = AlbumMapper.MapEditAlbumViewModel(model, userID);
            albumRepository.DeleteAlbum(album);

            List<Album> albumsDB = albumRepository.GettAllAlbumsByUserID(userID);
            List<ListAlbumViewModel> albums = new List<ListAlbumViewModel>();
            albumsDB.ForEach(x => albums.Add(AlbumMapper.MapListAlbumViewModel(x)));

            return PartialView("_Items", albums);
        }
    }
}

MVC/MVCLabb/Areas/User/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCLabb.Models;
using MVCLabb.Data;
using MVCLabb.Data.Repository;
using MVCLabb.HelperMethods;
using MVCLabb.Mapper;

namespace MVCLabb.Areas.User.Controllers
{
    [Authorize(Roles = "User")]
    public class CommentController : Controller
    {
        Guid userID;
        IUserRepository userRepository;
        ICommentRepository commentRepository;

        public CommentController()
        {
            userRepository = new UserRepository();
            commentRepository = new CommentRepository();
            userID = UserHelper.GetLogedInUser(userRepository).Id;

        }

        // GET: User/Comment
        public ActionResult Index(string id)
        {
            List<Comment> comments = commentRepository.GetAllComentsByPhotoID(id);
            List<CommentViewModel> model = new List<CommentViewModel>();
            comments.ForEach(x => model.Add(CommentMapper.MapCommentViewModel(x)));

            return View(model);
        }

        public ActionResult IndexAlbum(string id)
        {
            List<Comment> comments = commentRepository.GetAllComentsByAlbumID(id);
            List<CommentViewModel> model = new List<CommentViewModel>();
            comments.ForEach(x => model.Add(CommentMapper.MapCommentViewModel(x)));

            return View("Index", model);
        }

        [HttpGet]
        public ActionResult Delete(CommentViewModel model)
        {
            Comment comment = commentRepository.GetCommentByID(model.id);

            model = CommentMapper.MapCommentViewModel(comment);


            var photoid = comment.Photo != null ? comment.Photo.UserID : Guid.Empty;
            var albumid = comment.Album != null ? comment.Album.UserID : Guid.Empty;

            if (photoid == userID || albumid == userID)
            {
                return View(model);
            }
            return View();

        }

        [HttpPost]
        public ActionResult Delete(CommentViewModel model, FormCollection collection)
        {
            var comment = commentRepository.GetCommentByID(model.id);

            commentRepository.DeleteComment(comment);

            Guid id;
            List<CommentViewModel> models = new List<CommentViewModel>();
            if (comment.AlbumID == null ) {
                id = (Guid)comment.PhotoID;
                List<Comment> comments = commentRepository.GetAllComentsByPhotoID(id.ToString());
                comments.ForEach(x => models.Add(CommentMapper.MapCommentViewModel(x)));
            } else
            {
                id = (Guid)comment.AlbumID;
                List<Comment> comments = commentRepository.GetAllComentsByAlbumID(id.ToString());
                comments.ForEach(x => models.Add(CommentMapper.MapCommentViewModel(x)));
            }

            return PartialView("_Items", models);

        }
    }
}

MVC/MVCLabb/Areas/User/Controllers/PhotoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCLabb.Areas.User.Models;
using MVCLabb.Controllers;
using System.IO;
using MVCLabb.Data;
using MVCLabb.Data.Repository;
using MVCLabb.HelperMethods;
using MVCLabb.Areas.User.Mapper;

namespace MVCLabb.Areas.User.Controllers
{
    [Authorize(Roles = "User")]
    public class PhotoController : Controller
    {
        Guid userID;
        IUserRepository userRepository;
        IPhotoRepository photoRepository;
        IAlbumRepository albumRepository;

        public PhotoController()
        {
            userRepository = new UserRepository();
            photoRepository = new PhotoRepository();
            albumRepository = new AlbumRepository();
            userID = UserHelper.GetLogedInUser(userRepository).Id;

        }
        // GET: User/Edit
        public ActionResult Index()
        {
            List<Photo> photosFromDB = photoRepository.GetPhotoFromDbByUserId(userID);
            ICollection<IndexPhotoViewModels> model = new List<IndexPhotoViewModels>();
            photosFromDB.ForEach(x => model.Add(PhotoMapper.MapIndexPhotoViewModel(x)));

            return View(model);
            
        }


        // GET: User/Edit/Create
        public ActionResult Create()
        {
            var model = new CreatePhotoViewModels();
            var albums = albumRepository.GettAllAlbumsByUserID(userID);
            model.Albums.Add(new SelectListItem { Text = "Uncategorized", Value = "" });
            albums.ForEach(x => model.Albums.Add(new SelectListItem {Text = x.Name, Value = x.Id.ToString() }));

            return View(model);
        }

        // POST: User/Edit/Create
        [HttpPost]
        public ActionResult Create(CreatePhotoViewModels photo, HttpPostedFileBase photoUpload)
        {
            Photo photoToDB = PhotoMapper.MapCreatePhotoViewModel(photo);
            
            try
            {
                photoToDB.UserID = userID;
                photoToDB.Id = Guid.NewGuid();
                photoToDB.Date = DateTime.Now;
                photoToDB.Path = $" /Photos/{photoUpload.FileName}";
                photoRepository.AddPhotoToDB(photoToDB);

                photoUpload.SaveAs(Path.Combine(Server.MapPath("~/Photos"), photoUpload.FileName));
                return Content(photoUpload.FileName);
            }
            catch
            {
                var model = PhotoMapper.MapCreatePhotoViewModel(photoToDB);
                var albums = albumRepository.GettAllAlbumsByUserID(userID);
                model.Albums.Add(new SelectListItem { Text = "Uncategorized", Value = "" });
                albums.ForEach(x => model.Albums.Add(new SelectListItem { Text = x.Name, Value = x.Id.ToString() }));

                return Content(photoUpload.FileName);
            }
        }

        // GET: User/Edit/Edit/5
        public ActionResult Edit(EditPhotoViewModels photo)
        {
            Photo model = photoRepository.GetPhotoFromDbById(photo.Id);
            photo = PhotoMapper.MapEditPhotoViewModel(model);
            photo.AlbumId = model.AlbumID != null ? (Guid)model.AlbumID : Guid.Empty;
            var albums = albumRepository.GettAllAlbumsByUserID(userID);
            photo.Albums.Add(new SelectListItem { Text = "Uncategorized", Value = Guid.Empty.ToString() });
            albums.ForEach(x => photo.Albums.Add(new SelectListItem { Text = x.Name, Value = x.Id.ToString() }));

            if (model.UserID == userID)
                return View(photo);
            else
                return View();
                
        }

        // POST: User/Edit/Edit/5
        [HttpPost]
        public ActionResult Edit(EditPhotoViewModels photo, FormCollection collection)
        {
            Photo model = PhotoMapper.MapEditPhotoViewModel(photo);

            try
            {
                photoRepository.UdaptePhoto(model);
                return Content(photo.Name);
            }
            catch
            {
                return Content("Error");
            }
        }

        // GET: User/Edit/Delete/5
        public ActionResult Delete(DeletePhotoViewModels photo)
        {
            Photo model = photoRepository.GetPhotoFromDbById(photo.Id);
            photo = PhotoMapper.MapDeletePhotoViewModel(model);

            if (model.UserID == userID)
            {
                return View(photo);
            }
            else
            {
                return View();
            }
        }

        // POST: User/Edit/Delete/5
        [HttpPost]
        public ActionResult Delete(string Id)
        {
            
            try
            {
                Photo model = photoRepository.GetPhotoFromDbById(new Guid(Id));
                if (model.UserID == userID)
                {
                    photoRepository.DeletePhotoFromDB(model);

                    string fullPath = Request.MapPath(model.Path);

                    if (System.IO.File.Exists(fullPath))
                    {
                        System.IO.File.Delete(fullPath);
                    }

                }
                
            }
            catch
            {
                
            }
            List<Photo> photosFromDB = photoRepository.GetPhotoFromDbByUserId(userID);
            ICollection<IndexPhotoViewModels> models = new List<IndexPhotoViewModels>();
            photosFromDB.ForEach(x => models.Add(PhotoMapper.MapIndexPhotoViewModel(x)));


            return PartialView("_Images", models);
        }

    

    }
}

MVC/MVCLabb/Controllers/PhotoController.cs
using MVCLabb.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCLabb.Data;
using MVCLabb.Data.Repository;
using MVCLabb.Mapper;
using MVCLabb.HelperMethods;

namespace MVCLabb.Controllers
{
    public class PhotoController : Controller
    {

        IUserRepository userRepository;
        IPhotoRepository photoRepository;
        IAlbumRepository albumRepository;
        ICommentRepository commentRepository;

        public PhotoController()
        {
            userRepository = new UserRepository();
            photoRepository = new PhotoRepository();
            albumRepository = new AlbumRepository();
            commentRepository = new CommentRepository();

        }
        // GET: Photo
        [AllowAnonymous]
        public ActionResult Index()
        {
            List<Photo> photosFromDB = photoRepository.GetAllPhotosFromDb();
            List<IndexPhotoViewModel> photos = new List<IndexPhotoViewModel>();
            photosFromDB.ForEach(x => photos.Add(PhotoMapper.MapIndexPhotoViewModel(x)));

            return View(photos);
        }



        // GET: Photo/Details/5
        [AllowAnonymous]
        public ActionResult Details(DetailsPhotoViewModel photo)
        {
            Photo photoFromDB = photoRepository.GetPhotoFromDbById(photo.Id);
            photo = PhotoMapper.MapDetailsPhotoViewModel(photoFromDB);

            return PartialView("_PhotoDetail", photo);
        }

        [HttpPost]
        [Authorize]
        public ActionResult Details(DetailsPhotoViewModel photo, FormCollection collection)
        {
            var comment = new Comment
            {
                Date = DateTime.Now,
                Content = collection["comment"],
                UserID = UserHelper.GetLogedInUser(userRepository).Id,
                PhotoID = photo.Id
            };

            commentRepository.AddComment(comment);

            Photo photoFromDB = photoRepository.GetPhotoFromDbById(photo.Id);
            photo = PhotoMapper.MapDetailsPhotoViewModel(photoFromDB);

            return View(photo);
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult AlbumDetails(string id)
        {
            var album = albumRepository.GetAlbumByID(id);
            DetailAlbumViewModel model = AlbumMapper.MapDetailAlbumViewModel(album);

            return PartialView("_AlbumDetails", model);
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult AlbumPhotoes(string id)
        {

            
                List<Photo> photosFromDB = photoRepository.GetAllPhotoesInAlbumByID(id);
                List<IndexPhotoViewModel> photos = new List<IndexPhotoViewModel>();
                photosFromDB.ForEach(x => photos.Add(PhotoMapper.MapIndexPhotoViewModel(x)));
                return PartialView("_thumbnails", photos);


        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult AlbumComments(string id)
        {
            List<Comment> comments = commentRepository.GetAllComentsByAlbumID(id).OrderBy(x => x.Date).ToList();
            List<CommentViewModel> model = new List<CommentViewModel>();
            comments.ForEach(x => model.Add(CommentMapper.MapCommentViewModel(x)));



            return Json(model, JsonRequestBehavior.AllowGet);


        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult AlbumComments(string id, string comment)
        {
            Guid userID = UserHelper.GetLogedInUser(userRepository).Id;

            var comm = new Comment {
                AlbumID = new Guid(id),
                Date = DateTime.Now,
                Content = comment,
                Id = Guid.NewGuid(),
                UserID = userID
            };

            commentRepository.AddComment(comm);

            List<Comment> comments = commentRepository.GetAllComentsByAlbumID(id.ToString()).OrderBy(x => x.Date).ToList();
            List<CommentViewModel> model = new List<CommentViewModel>();
            comments.ForEach(x => model.Add(CommentMapper.MapCommentViewModel(x)));



            return Json(model);


        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult PhotoComments(string id)
        {
            List<Comment> comments = commentRepository.GetAllComentsByPhotoID(id).OrderBy(x => x.Date).ToList();
            List<CommentViewModel> model = new List<CommentViewModel>();
            comments.ForEach(x => model.Add(CommentMapper.MapCommentViewModel(x)));



            return Json(model, JsonRequestBehavior.AllowGet);


        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult PhotoComments(string id, string comment)
        {
            Guid userID = UserHelper.GetLogedInUser(userRepository).Id;

            var comm = new Comment
            {
                PhotoID = new Guid(id),
                Date = DateTime.Now,
                Content = comment,
                Id = Guid.NewGuid(),
                UserID = userID
            };

            commentRepository.AddComment(comm);

            List<Comment> comments = commentRepository.GetAllComentsByAlbumID(id.ToString()).OrderBy(x => x.Date).ToList();
            List<CommentViewModel> model = new List<CommentViewModel>();
            comments.ForEach(x => model.Add(CommentMapper.MapCommentViewModel(x)));



            return Json(model);


        }
    }
}

MVC/MVCLabb/Areas/User/Views/Photo/Create.cshtml
@model MVCLabb.Areas.User.Models.CreatePhotoViewModels

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Photo</h2>

@using (Html.BeginForm("Create", "Photo", FormMethod.Post, new { id = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Upload</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Albums, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.AlbumId, Model.Albums, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Albums, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <label class="control-label col-md-2">Bild</label>
            <div class="col-md-10">
                <input type="file" name="photoUpload" id="photoUpload" class="form-control" required />
            </div>

            <div class="form-group">

                <label class="control-label col-md-2"></label>
                <div class="col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" id="submit" style="margin-top: 10px; margin-left: 10px;" />
                </div>

            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    <script>

        var form = $('#form');


        form.submit(function (e) {
            e.preventDefault();

            swal({
                title: "Upload imaga",
                text: "Submit to upload",
                type: "info",
                showCancelButton: true,
                closeOnConfirm: false,
                showLoaderOnConfirm: true
            }, function () {

                $.ajax({
                    type: "POST",
                    url: "/User/Photo/Create",
                    data: new FormData(form[0]),
                    success: function (data) {
                        swal("Sucsess", data + " Uploaded")
                        form[0].reset();
                    },
                    error: function (e) {
                        swal("Error!", "Something went wrong!", "error")
                    },
                    processData: false,
                    contentType: false
                });

            });

        });
    </script>
}

MVC/MVCLabb/Areas/User/Views/Photo/Delete.cshtml
@model MVCLabb.Areas.User.Models.DeletePhotoViewModels

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Photo</h2>

<h3>Delete</h3>
<div>
    <h4>Are you sure you want to delete this?</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            
        </dt>
        <dd>
            <img src="@Model.Path" alt="@Model.Name" style="max-width: 200px;"/>
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Path)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Path)
        </dd>

    </dl>

    @using (Html.BeginForm("Photo", "Detete", FormMethod.Post, new { id = "form" })) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVC/MVCLabb/Areas/User/Views/Photo/Edit.cshtml
@model MVCLabb.Areas.User.Models.EditPhotoViewModels

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Photo</h2>

@using (Html.BeginForm("Edit", "Photo", FormMethod.Post, new { id = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Edit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            <label class="control-label col-md-2"></label>
            <div class="col-md-5">
                <img src="@Model.Path" alt="@Model.Name" style="max-width: 100%;" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Albums, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.AlbumId, Model.Albums, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Albums, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            
            <div class="col-md-offset-2 col-md-10">
  
                @Html.ActionLink($"Edit Comments ({Model.Comments.Count()})", "Index", "Comment", new { id = Model.Id }, null)
                <br />
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    <script>

        var form = $('#form');

        form.submit(function (e) {
            e.preventDefault();

            swal({
                title: "Save!",
                text: "Do you want to save edited changes?",
                type: "info",
                showCancelButton: true,
                closeOnConfirm: false,
                showLoaderOnConfirm: true
            }, function () {

                $.ajax({
                    type: "POST",
                    url: "/User/Photo/Edit",
                    data: new FormData(form[0]),
                    success: function (data) {
                        swal("Sucsess", data + " saved")
                    },
                    error: function (e) {
                        swal("Error!", "Something went wrong!", "error")
                    },
                    processData: false,
                    contentType: false
                });

            });

        });

        $("#AlbumId").val('@Model.AlbumId');
    </script>
}

MVC/MVCLabb/Areas/User/Views/Photo/Index.cshtml
@model IEnumerable<MVCLabb.Areas.User.Models.IndexPhotoViewModels>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Photos</h2>

<p>
    @Html.ActionLink("Add New Photo", "Create") |
    @Html.ActionLink("Manage Albums", "Index", "Album")
</p>
<div id="content">

    <table class="table">
        <tr>
            <th>
                Image
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Path)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Album)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Comments)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <img src="@item.Path" alt="@item.Name" style="max-width: 100px;" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Path)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Album)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Comments)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", null, new { id = item.Id, @class = "delete" })
                </td>
            </tr>
        }

    </table>

</div>

@section Scripts {
    <script>

        function SetDelete() { 

        $('.delete').each(function () {

            $(this).click(function (e) {
                e.preventDefault();

                var model = {
                    Id: ""
                };

                model.Id = this.id;

                swal({
                    title: "Are you sure?",
                    text: "Your will not be able to recover this imaginary file!",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonClass: "btn-danger",
                    confirmButtonText: "Yes, delete it!",
                    closeOnConfirm: false
                }, function () {

                    $.ajax({
                        type: "POST",
                        url: "/User/Photo/Delete",
                        data: JSON.stringify(model),
                        success: function (data) {
                            swal("Image is deleted", "success")
                            $('#content').html(data);
                            SetDelete();
                            
                        },
                        error: function (e) {
                            swal("Error!", "Something went wrong!", "error")
                        },
                        contentType: "application/json; charset=utf-8",
                        dataType: "text"
                    });

                });

            });
        
        });
        };

        SetDelete();
       
    </script>
}

MVC/MVCLabb/Areas/User/Views/Photo/_Images.cshtml
@model IEnumerable<MVCLabb.Areas.User.Models.IndexPhotoViewModels>

<table class="table">
    <tr>
        <th>
            Image
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Path)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Album)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Comments)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <img src="@item.Path" alt="@item.Name" style="max-width: 100px;" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Path)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Album)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comments)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", null, new { id = item.Id, @class = "delete" })
            </td>
        </tr>
    }

</table>